apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tcy02bgmq-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tcy02bgmq-java-quarkus-gitops